logging.level:
  org.springframework.security: TRACE

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "PLACEHOLDER"
            client-secret: "PLACEHOLDER"
